# Generated by Django 2.0.5 on 2018-07-13 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('receive_email', models.IntegerField(default=1)),
                ('password', models.CharField(max_length=255)),
                ('admin', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('noti_noti', models.IntegerField(default=0)),
                ('noti_chat', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'agents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'departments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('chat', models.CharField(max_length=30, null=True)),
                ('content', models.TextField()),
                ('status', models.IntegerField(default=0)),
                ('datestart', models.DateTimeField()),
                ('dateend', models.DateTimeField()),
                ('attach', models.FileField(blank=True, null=True, upload_to='photos')),
            ],
            options={
                'db_table': 'tickets',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TopicAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentid', models.ForeignKey(db_column='agentid', on_delete=django.db.models.deletion.CASCADE, to='FirstAPI.Agents')),
            ],
            options={
                'db_table': 'topic_agent',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('departmentid', models.ForeignKey(db_column='departmentid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='FirstAPI.Departments')),
            ],
            options={
                'db_table': 'topics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255, null=True)),
                ('receive_email', models.IntegerField(default=1)),
                ('status', models.IntegerField(default=0)),
                ('created', models.DateTimeField()),
                ('noti_noti', models.IntegerField(default=0)),
                ('noti_chat', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='topicagent',
            name='topicid',
            field=models.ForeignKey(db_column='topicid', on_delete=django.db.models.deletion.CASCADE, to='FirstAPI.Topics'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='sender',
            field=models.ForeignKey(db_column='sender', on_delete=django.db.models.deletion.CASCADE, to='FirstAPI.Users'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='topicid',
            field=models.ForeignKey(db_column='topicid', on_delete=django.db.models.deletion.DO_NOTHING, to='FirstAPI.Topics'),
        ),
        migrations.AddField(
            model_name='agents',
            name='departmentid',
            field=models.ForeignKey(db_column='departmentid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='FirstAPI.Departments'),
        ),
    ]
